//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Serves as the abstract base class for wrapper classes that provide access to DOM instances.
	/// The <see cref="DomInstanceBase"/> class defines the common functionality and structure for interacting with DOM objects stored in the database, serving as a foundation for derived classes that wrap specific DOM instances.
	/// </summary>
	public abstract class DomInstanceBase : IEquatable<DomInstanceBase>
	{
		protected DomInstanceBase(DomDefinitionId id)
		{
			if (id == null)
				throw new ArgumentNullException("id");
			domInstance = new DomInstance { DomDefinitionId = id };
		}

		protected DomInstanceBase(DomInstance domInstance)
		{
			if (domInstance == null)
				throw new ArgumentNullException("domInstance");
			this.domInstance = domInstance;
		}

		/// <summary>
		/// Gets the Module ID of the DOM Instance.
		/// </summary>
		public String ModuleId
		{
			get
			{
				return domInstance.DomDefinitionId.ModuleId;
			}
		}

		/// <summary>
		/// Gets the ID of the DOM Instance.
		/// </summary>
		public DomInstanceId ID
		{
			get
			{
				return domInstance.ID;
			}
		}

		/// <summary>
		/// Gets the name of the DOM Instance.
		/// </summary>
		public String Name
		{
			get
			{
				return domInstance.Name;
			}
		}

		/// <summary>
		/// Gets the Status ID of the DOM Instance.
		/// </summary>
		public String StatusId
		{
			get
			{
				return domInstance.StatusId;
			}
		}

		/// <summary>
		/// Gets the underlying DOM Instance.
		/// </summary>
		public DomDefinitionId DomDefinitionId
		{
			get
			{
				return domInstance.DomDefinitionId;
			}
		}

		protected DomInstance domInstance { get; set; }

		public static implicit operator DomInstance(DomInstanceBase instance)
		{
			return instance.ToInstance();
		}

		public static bool operator ==(DomInstanceBase left, DomInstanceBase right)
		{
			if (left is null)
			{
				return right is null;
			}

			return left.Equals(right);
		}

		public static bool operator !=(DomInstanceBase left, DomInstanceBase right)
		{
			return !(left == right);
		}

		/// <summary>
		/// Deletes this DOM Instance from the database.
		/// </summary>
		/// <param name="messageHandler">The connection to the DataMiner system.</param>
		public void Delete(Func<DMSMessage[], DMSMessage[]> messageHandler)
		{
			Delete(new DomHelper(messageHandler, ModuleId));
		}

		/// <summary>
		/// Deletes this DOM Instance from the database.
		/// </summary>
		/// <param name="helper">The connection to the DataMiner system.</param>
		public void Delete(DomHelper helper)
		{
			helper.DomInstances.Delete(domInstance);
		}

		/// <summary>
		/// Saves this DOM Instance to the database.
		/// </summary>
		/// <param name="messageHandler">The connection to the DataMiner system.</param>
		public void Save(Func<DMSMessage[], DMSMessage[]> messageHandler)
		{
			Save(new DomHelper(messageHandler, ModuleId));
		}

		/// <summary>
		/// Saves this DOM Instance to the database.
		/// </summary>
		/// <param name="helper">The connection to the DataMiner system.</param>
		public abstract void Save(DomHelper helper);
		/// <summary>
		/// Return the DOM Instance object with all the fields filled in according to this object.
		/// </summary>
		public DomInstance ToInstance()
		{
			BeforeToInstance();
			var instance = InternalToInstance();
			AfterToInstance();
			return instance;
		}

		/// <summary>
		/// Optional method that runs before the internal ToInstance method runs.
		/// </summary>
		protected virtual void BeforeToInstance()
		{
		}

		/// <summary>
		/// Return the DOM Instance object with all the fields filled in according to this object.
		/// </summary>
		protected abstract DomInstance InternalToInstance();
		/// <summary>
		/// Optional method that runs after the internal ToInstance method runs.
		/// </summary>
		protected virtual void AfterToInstance()
		{
		}

		protected abstract void InitializeProperties();
		/// <summary>
		/// Optional method that runs after the object is constructed and the initialize has ran.
		/// </summary>
		protected virtual void AfterLoad()
		{
		}

		public override int GetHashCode()
		{
			return this.ID.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			return Equals(obj as DomInstanceBase);
		}

		public bool Equals(DomInstanceBase other)
		{
			if (other is null)
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			return this.ID.Equals(other.ID);
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model
{
	using System;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public abstract class DomSectionBase : IEquatable<DomSectionBase>
	{
		protected Section section;
		protected DomSectionBase(SectionDefinitionID id)
		{
			if (id == null)
				throw new ArgumentNullException("id");
			this.section = new Section(id);
			AfterLoad();
		}

		protected DomSectionBase(SectionDefinition definition)
		{
			if (definition == null)
				throw new ArgumentNullException("definition");
			this.section = new Section(definition);
			AfterLoad();
		}

		protected DomSectionBase(Section section, SectionDefinitionID id)
		{
			if (section == null)
				throw new ArgumentNullException("section");
			if (section.SectionDefinitionID == null)
			{
				throw new ArgumentException("The given section doesn't have a valid SectionDefinitionId.", nameof(section));
			}

			if (!section.SectionDefinitionID.Equals(id))
			{
				throw new ArgumentException($"The given section, is not of type '{nameof(id)}'", nameof(section));
			}

			this.section = section;
			AfterLoad();
		}

		/// <summary>
		/// Gets the section's ID.
		/// </summary>
		public SectionID ID
		{
			get
			{
				return section.ID;
			}
		}

		/// <summary>
		/// Gets the section's Section Definition ID.
		/// </summary>
		public SectionDefinitionID SectionDefinitionID
		{
			get
			{
				return section.SectionDefinitionID;
			}
		}

		/// <summary>
		/// Gets a value indicating whether the section is empty.
		/// </summary>
		/// <value>
		/// <see langword="true"/> if the section doesn't contains any field values, otherwise, <see langword="false"/>.
		/// </value>
		public bool IsEmpty
		{
			get
			{
				return !section.FieldValues.Any();
			}
		}

		public static implicit operator SectionDefinitionID(DomSectionBase sectionBase)
		{
			return sectionBase.section.SectionDefinitionID;
		}

		public static implicit operator SectionDefinition(DomSectionBase sectionBase)
		{
			return sectionBase.section.GetSectionDefinition();
		}

		public static bool operator ==(DomSectionBase left, DomSectionBase right)
		{
			if (left is null)
			{
				return right is null;
			}

			return left.Equals(right);
		}

		public static bool operator !=(DomSectionBase left, DomSectionBase right)
		{
			return !(left == right);
		}

		public override string ToString()
		{
			return $"{this.section.SectionDefinitionID}";
		}

		/// <summary>
		/// Optional method that runs at the end of the constructor.
		/// </summary>
		protected virtual void AfterLoad()
		{
		}

		public virtual Section ToSection()
		{
			BeforeToSection();
			var section = InternalToSection();
			AfterToSection();
			return section;
		}

		/// <summary>
		/// Optional method that runs before the internal ToSection method runs.
		/// </summary>
		protected virtual void BeforeToSection()
		{
		}

		protected virtual Section InternalToSection()
		{
			return this.section;
		}

		/// <summary>
		/// Optional method that runs after the internal ToSection method runs.
		/// </summary>
		protected virtual void AfterToSection()
		{
		}

		public override int GetHashCode()
		{
			return this.ID.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			return Equals(obj as DomSectionBase);
		}

		public bool Equals(DomSectionBase other)
		{
			if (other is null)
			{
				return false;
			}

			if (ReferenceEquals(this, other))
			{
				return true;
			}

			return this.ID.Equals(other.ID);
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcConnectivityManagement
{
	using System;
	using System.ComponentModel;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class SlcConnectivityManagementIds
	{
		public const string ModuleId = "(slc)connectivity_management";
		public static class Enums
		{
			public enum Role
			{
				Source = 0,
				Destination = 1
			}
		}

		public static class Sections
		{
			public static class CategoryInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("11767eb4-9c02-4811-af4d-e6a6f8b460e8"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("6827feae-88af-428b-803e-947713d10318"));
				public static FieldDescriptorID ParentCategory { get; } = new FieldDescriptorID(new Guid("950fd43f-2c5d-45bf-aa51-a61324cd07f5"));
			}

			public static class VirtualSignalGroupLevels
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("5e0dcb70-3dbc-479d-a127-c2e062e49b40"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Endpoint { get; } = new FieldDescriptorID(new Guid("6cbd74f3-e34f-48c7-a033-aaa16a0ba36e"));
				public static FieldDescriptorID Level { get; } = new FieldDescriptorID(new Guid("764c6435-04c7-448d-a2ec-0a4ea43b4b7d"));
			}

			public static class ConnectionInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("41c79ebb-f6c0-4601-a891-335770a9eed8"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Destination { get; } = new FieldDescriptorID(new Guid("83e65e2f-dbdc-410b-bb76-b38d1cc03935"));
				public static FieldDescriptorID IsConnected { get; } = new FieldDescriptorID(new Guid("72f8694c-abda-4a18-b5ee-029c9cb5c945"));
				public static FieldDescriptorID ConnectedSource { get; } = new FieldDescriptorID(new Guid("811b70b7-c5db-429c-9c1e-af7b0f39ffba"));
				public static FieldDescriptorID PendingConnectedSource { get; } = new FieldDescriptorID(new Guid("a6a5d036-0541-4041-8f39-9b676b757ee9"));
			}

			public static class VirtualSignalGroupInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("a7d8863e-82d4-4bf3-a4c5-f34b1fb7eac0"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("f644dc13-d3e0-46df-b12d-4869c58e04f8"));
				public static FieldDescriptorID Description { get; } = new FieldDescriptorID(new Guid("e080c1da-879f-4cf1-973c-acbf01aca25c"));
				public static FieldDescriptorID Role { get; } = new FieldDescriptorID(new Guid("5b615da1-5772-4497-b0e9-2cdaf8822d65"));
				public static FieldDescriptorID Categories { get; } = new FieldDescriptorID(new Guid("3d419cab-6c82-4297-9199-d85a5ae12afb"));
			}

			public static class EndpointInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("4b094feb-3e2a-4539-ad1c-3e15c4dd7669"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("dabc33a4-0682-46f3-9b96-7b9c4abe2d4e"));
				public static FieldDescriptorID Role { get; } = new FieldDescriptorID(new Guid("10e9cf97-59e0-4c08-8cea-9f737a9ee7f8"));
				public static FieldDescriptorID Element { get; } = new FieldDescriptorID(new Guid("8c19dd88-d75a-42ea-928c-4508970778f4"));
				public static FieldDescriptorID Identifier { get; } = new FieldDescriptorID(new Guid("89cb7302-93f5-4c1e-ab97-d986c0353ad2"));
				public static FieldDescriptorID ControlElement { get; } = new FieldDescriptorID(new Guid("c1bda8e0-0380-4ecf-bb61-0db25ef8412a"));
				public static FieldDescriptorID ControlIdentifier { get; } = new FieldDescriptorID(new Guid("48575262-2b0b-404f-a4c7-22fd104e0426"));
				public static FieldDescriptorID TransportMetadata { get; } = new FieldDescriptorID(new Guid("b6fd7817-4524-420d-9497-8bb4edccdd9e"));
				public static FieldDescriptorID TransportType { get; } = new FieldDescriptorID(new Guid("64cc245e-5a0a-4479-9766-a93a7c090255"));
			}

			public static class TransportTypeTsoip
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("6d130f78-b4f4-4ee1-974d-27997a57502e"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID SourceIP { get; } = new FieldDescriptorID(new Guid("a77067fb-c978-4c19-862c-871015609518"));
				public static FieldDescriptorID MulticastIP { get; } = new FieldDescriptorID(new Guid("17fd8b18-bce5-4dd5-9892-ace39e8e01b0"));
				public static FieldDescriptorID Port { get; } = new FieldDescriptorID(new Guid("4608640f-fda1-4bf9-98c2-2e7d752ad6cf"));
			}

			public static class TransportTypeInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("57558fef-283c-4b4d-84f8-f411a26e546c"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("2442cdc4-aa19-40b5-bb53-281f4a33aa74"));
			}

			public static class LevelInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("dd22ecda-43d1-40b5-b37a-45ab8ae5d3f9"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Number { get; } = new FieldDescriptorID(new Guid("07c316a4-0cd0-443e-98ce-7012d50a1f33"));
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("ddc1105e-2213-4ca9-bc1a-0077ee2cb198"));
				public static FieldDescriptorID TransportType { get; } = new FieldDescriptorID(new Guid("0154f612-029e-4b94-a92e-3572950bfe4d"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId Level { get; } = new DomDefinitionId(new Guid("3a016709-8fe1-4ad6-aa1d-56873492b80b"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId Connection { get; } = new DomDefinitionId(new Guid("bd002264-444c-4429-ac4a-6ff69c3939a7"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId Category { get; } = new DomDefinitionId(new Guid("9319d52c-7605-4aab-a340-bd54d140a0ba"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId Endpoint { get; } = new DomDefinitionId(new Guid("3d952eea-dd7f-4997-acec-af888160392a"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId VirtualSignalGroup { get; } = new DomDefinitionId(new Guid("f23a6e99-cb88-4282-bbbe-7ade9bc7fb04"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId TransportType { get; } = new DomDefinitionId(new Guid("91ddfbfe-00db-4244-b8e3-5a0a08fa3ced"))
			{ ModuleId = "(slc)connectivity_management" };
		}

		public static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcConnectivityManagement
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a LevelInstance DOM instance.
	/// The <see cref="LevelInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class LevelInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInstance"/> class. Creates an empty <see cref="LevelInstance"/> instance with default settings.
		/// </summary>
		public LevelInstance() : base(SlcConnectivityManagementIds.Definitions.Level)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="LevelInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public LevelInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.Level))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.Level)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the LevelInfo section of the DOM Instance.
		/// </summary>
		public LevelInfoSection LevelInfo { get; set; }

		public static explicit operator LevelInstance(DomInstance instance)
		{
			return new LevelInstance(instance);
		}

		/// <inheritdoc />
		protected override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(LevelInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected override void InitializeProperties()
		{
			var _levelInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.LevelInfo.Id));
			if (_levelInfo is null)
			{
				LevelInfo = new LevelInfoSection();
			}
			else
			{
				LevelInfo = new LevelInfoSection(_levelInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a ConnectionInstance DOM instance.
	/// The <see cref="ConnectionInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class ConnectionInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionInstance"/> class. Creates an empty <see cref="ConnectionInstance"/> instance with default settings.
		/// </summary>
		public ConnectionInstance() : base(SlcConnectivityManagementIds.Definitions.Connection)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="ConnectionInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ConnectionInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.Connection))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.Connection)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the ConnectionInfo section of the DOM Instance.
		/// </summary>
		public ConnectionInfoSection ConnectionInfo { get; set; }

		public static explicit operator ConnectionInstance(DomInstance instance)
		{
			return new ConnectionInstance(instance);
		}

		/// <inheritdoc />
		protected override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(ConnectionInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected override void InitializeProperties()
		{
			var _connectionInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.ConnectionInfo.Id));
			if (_connectionInfo is null)
			{
				ConnectionInfo = new ConnectionInfoSection();
			}
			else
			{
				ConnectionInfo = new ConnectionInfoSection(_connectionInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryInstance DOM instance.
	/// The <see cref="CategoryInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class CategoryInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class. Creates an empty <see cref="CategoryInstance"/> instance with default settings.
		/// </summary>
		public CategoryInstance() : base(SlcConnectivityManagementIds.Definitions.Category)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="CategoryInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.Category))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.Category)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the CategoryInfo section of the DOM Instance.
		/// </summary>
		public CategoryInfoSection CategoryInfo { get; set; }

		public static explicit operator CategoryInstance(DomInstance instance)
		{
			return new CategoryInstance(instance);
		}

		/// <inheritdoc />
		protected override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(CategoryInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected override void InitializeProperties()
		{
			var _categoryInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.CategoryInfo.Id));
			if (_categoryInfo is null)
			{
				CategoryInfo = new CategoryInfoSection();
			}
			else
			{
				CategoryInfo = new CategoryInfoSection(_categoryInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a EndpointInstance DOM instance.
	/// The <see cref="EndpointInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class EndpointInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInstance"/> class. Creates an empty <see cref="EndpointInstance"/> instance with default settings.
		/// </summary>
		public EndpointInstance() : base(SlcConnectivityManagementIds.Definitions.Endpoint)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="EndpointInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public EndpointInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.Endpoint))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.Endpoint)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the EndpointInfo section of the DOM Instance.
		/// </summary>
		public EndpointInfoSection EndpointInfo { get; set; }

		/// <summary>
		/// Gets or sets the TransportTypeTsoip section of the DOM Instance.
		/// </summary>
		public TransportTypeTsoipSection TransportTypeTsoip { get; set; }

		public static explicit operator EndpointInstance(DomInstance instance)
		{
			return new EndpointInstance(instance);
		}

		/// <inheritdoc />
		protected override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(EndpointInfo.ToSection());
			if (!TransportTypeTsoip.IsEmpty)
			{
				domInstance.Sections.Add(TransportTypeTsoip.ToSection());
			}

			return domInstance;
		}

		/// <inheritdoc />
		public override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected override void InitializeProperties()
		{
			var _endpointInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.EndpointInfo.Id));
			if (_endpointInfo is null)
			{
				EndpointInfo = new EndpointInfoSection();
			}
			else
			{
				EndpointInfo = new EndpointInfoSection(_endpointInfo);
			}

			var _transportTypeTsoip = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.Id));
			if (_transportTypeTsoip is null)
			{
				TransportTypeTsoip = new TransportTypeTsoipSection();
			}
			else
			{
				TransportTypeTsoip = new TransportTypeTsoipSection(_transportTypeTsoip);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupInstance DOM instance.
	/// The <see cref="VirtualSignalGroupInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class VirtualSignalGroupInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInstance"/> class. Creates an empty <see cref="VirtualSignalGroupInstance"/> instance with default settings.
		/// </summary>
		public VirtualSignalGroupInstance() : base(SlcConnectivityManagementIds.Definitions.VirtualSignalGroup)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="VirtualSignalGroupInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.VirtualSignalGroup))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.VirtualSignalGroup)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the VirtualSignalGroupLevels section of the DOM Instance.
		/// </summary>
		public IList<VirtualSignalGroupLevelsSection> VirtualSignalGroupLevels { get; private set; }

		/// <summary>
		/// Gets or sets the VirtualSignalGroupInfo section of the DOM Instance.
		/// </summary>
		public VirtualSignalGroupInfoSection VirtualSignalGroupInfo { get; set; }

		public static explicit operator VirtualSignalGroupInstance(DomInstance instance)
		{
			return new VirtualSignalGroupInstance(instance);
		}

		/// <inheritdoc />
		protected override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			foreach (var item in VirtualSignalGroupLevels)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			domInstance.Sections.Add(VirtualSignalGroupInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected override void InitializeProperties()
		{
			VirtualSignalGroupLevels = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Id)).Select(section => new VirtualSignalGroupLevelsSection(section)).ToList();
			var _virtualSignalGroupInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Id));
			if (_virtualSignalGroupInfo is null)
			{
				VirtualSignalGroupInfo = new VirtualSignalGroupInfoSection();
			}
			else
			{
				VirtualSignalGroupInfo = new VirtualSignalGroupInfoSection(_virtualSignalGroupInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a TransportTypeInstance DOM instance.
	/// The <see cref="TransportTypeInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class TransportTypeInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInstance"/> class. Creates an empty <see cref="TransportTypeInstance"/> instance with default settings.
		/// </summary>
		public TransportTypeInstance() : base(SlcConnectivityManagementIds.Definitions.TransportType)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="TransportTypeInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public TransportTypeInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.TransportType))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.TransportType)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the TransportTypeInfo section of the DOM Instance.
		/// </summary>
		public TransportTypeInfoSection TransportTypeInfo { get; set; }

		public static explicit operator TransportTypeInstance(DomInstance instance)
		{
			return new TransportTypeInstance(instance);
		}

		/// <inheritdoc />
		protected override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(TransportTypeInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected override void InitializeProperties()
		{
			var _transportTypeInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Id));
			if (_transportTypeInfo is null)
			{
				TransportTypeInfo = new TransportTypeInfoSection();
			}
			else
			{
				TransportTypeInfo = new TransportTypeInfoSection(_transportTypeInfo);
			}
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcConnectivityManagement
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a CategoryInfoSection section.
	/// The <see cref="CategoryInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class CategoryInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class. Creates an empty <see cref="CategoryInfoSection"/> object with default settings.
		/// </summary>
		public CategoryInfoSection() : base(SlcConnectivityManagementIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CategoryInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="CategoryInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public CategoryInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.CategoryInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.CategoryInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.CategoryInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.CategoryInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ParentCategory field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? ParentCategory
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.CategoryInfo.ParentCategory);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.CategoryInfo.ParentCategory);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.CategoryInfo.ParentCategory, (Guid)value);
				}
			}
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.CategoryInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupLevelsSection section.
	/// The <see cref="VirtualSignalGroupLevelsSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class VirtualSignalGroupLevelsSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupLevelsSection"/> class. Creates an empty <see cref="VirtualSignalGroupLevelsSection"/> object with default settings.
		/// </summary>
		public VirtualSignalGroupLevelsSection() : base(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupLevelsSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="VirtualSignalGroupLevelsSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupLevelsSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Endpoint field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Endpoint
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Endpoint);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Endpoint);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Endpoint, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Level field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Level
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Level);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Level);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Level, (Guid)value);
				}
			}
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Endpoint) == null)
				throw new InvalidOperationException("'Endpoint' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevels.Level) == null)
				throw new InvalidOperationException("'Level' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a ConnectionInfoSection section.
	/// The <see cref="ConnectionInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class ConnectionInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionInfoSection"/> class. Creates an empty <see cref="ConnectionInfoSection"/> object with default settings.
		/// </summary>
		public ConnectionInfoSection() : base(SlcConnectivityManagementIds.Sections.ConnectionInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="ConnectionInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ConnectionInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.ConnectionInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Destination field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Destination
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.ConnectionInfo.Destination);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.ConnectionInfo.Destination);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.ConnectionInfo.Destination, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the IsConnected field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Boolean? IsConnected
		{
			get
			{
				var wrapper = section.GetValue<Boolean>(SlcConnectivityManagementIds.Sections.ConnectionInfo.IsConnected);
				if (wrapper != null)
				{
					return (Boolean?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.ConnectionInfo.IsConnected);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.ConnectionInfo.IsConnected, (Boolean)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ConnectedSource field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? ConnectedSource
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.ConnectionInfo.ConnectedSource);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.ConnectionInfo.ConnectedSource);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.ConnectionInfo.ConnectedSource, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the PendingConnectedSource field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? PendingConnectedSource
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.ConnectionInfo.PendingConnectedSource);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.ConnectionInfo.PendingConnectedSource);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.ConnectionInfo.PendingConnectedSource, (Guid)value);
				}
			}
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.ConnectionInfo.Destination) == null)
				throw new InvalidOperationException("'Destination' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Boolean>(SlcConnectivityManagementIds.Sections.ConnectionInfo.IsConnected) == null)
				throw new InvalidOperationException("'IsConnected' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupInfoSection section.
	/// The <see cref="VirtualSignalGroupInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class VirtualSignalGroupInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInfoSection"/> class. Creates an empty <see cref="VirtualSignalGroupInfoSection"/> object with default settings.
		/// </summary>
		public VirtualSignalGroupInfoSection() : base(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Id)
		{
			Categories = new List<Guid>();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="VirtualSignalGroupInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Id)
		{
			var categories = section.GetListValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Categories);
			Categories = categories != null ? categories.Values : new List<Guid>();
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Description field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Description
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Description);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Description);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Description, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Role field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcConnectivityManagementIds.Enums.Role? Role
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role);
				if (wrapper != null)
				{
					return (SlcConnectivityManagementIds.Enums.Role?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Categories field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public IList<Guid> Categories { get; private set; }

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role) == null)
				throw new InvalidOperationException("'Role' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (Categories.Count == 0)
				section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Categories);
			else
				section.AddOrUpdateListValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Categories, Categories.ToList());
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a EndpointInfoSection section.
	/// The <see cref="EndpointInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class EndpointInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInfoSection"/> class. Creates an empty <see cref="EndpointInfoSection"/> object with default settings.
		/// </summary>
		public EndpointInfoSection() : base(SlcConnectivityManagementIds.Sections.EndpointInfo.Id)
		{
			TransportMetadata = new List<Guid>();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="EndpointInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public EndpointInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.EndpointInfo.Id)
		{
			var transportMetadata = section.GetListValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportMetadata);
			TransportMetadata = transportMetadata != null ? transportMetadata.Values : new List<Guid>();
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Role field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcConnectivityManagementIds.Enums.Role? Role
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.EndpointInfo.Role);
				if (wrapper != null)
				{
					return (SlcConnectivityManagementIds.Enums.Role?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Role);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Role, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Element field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Element
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Element);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Element);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Element, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Identifier field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Identifier
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Identifier);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Identifier);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Identifier, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ControlElement field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ControlElement
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlElement);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlElement);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlElement, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ControlIdentifier field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ControlIdentifier
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlIdentifier);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlIdentifier);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlIdentifier, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the TransportMetadata field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public IList<Guid> TransportMetadata { get; private set; }

		/// <summary>
		/// Gets or sets the TransportType field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? TransportType
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType, (Guid)value);
				}
			}
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.EndpointInfo.Role) == null)
				throw new InvalidOperationException("'Role' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (TransportMetadata.Count == 0)
				section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportMetadata);
			else
				section.AddOrUpdateListValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportMetadata, TransportMetadata.ToList());
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType) == null)
				throw new InvalidOperationException("'TransportType' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a TransportTypeTsoipSection section.
	/// The <see cref="TransportTypeTsoipSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class TransportTypeTsoipSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeTsoipSection"/> class. Creates an empty <see cref="TransportTypeTsoipSection"/> object with default settings.
		/// </summary>
		public TransportTypeTsoipSection() : base(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeTsoipSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="TransportTypeTsoipSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public TransportTypeTsoipSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.TransportTypeTsoip.Id)
		{
		}

		/// <summary>
		/// Gets or sets the SourceIP field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String SourceIP
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.SourceIP);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.SourceIP);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.SourceIP, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the MulticastIP field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String MulticastIP
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.MulticastIP);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.MulticastIP);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.MulticastIP, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Port field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Int64? Port
		{
			get
			{
				var wrapper = section.GetValue<Int64>(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.Port);
				if (wrapper != null)
				{
					return (Int64?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.Port);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.Port, (Int64)value);
				}
			}
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeTsoip.MulticastIP) == null)
				throw new InvalidOperationException("'MulticastIP' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a TransportTypeInfoSection section.
	/// The <see cref="TransportTypeInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class TransportTypeInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInfoSection"/> class. Creates an empty <see cref="TransportTypeInfoSection"/> object with default settings.
		/// </summary>
		public TransportTypeInfoSection() : base(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="TransportTypeInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public TransportTypeInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.TransportTypeInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name, (String)value);
				}
			}
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a LevelInfoSection section.
	/// The <see cref="LevelInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class LevelInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInfoSection"/> class. Creates an empty <see cref="LevelInfoSection"/> object with default settings.
		/// </summary>
		public LevelInfoSection() : base(SlcConnectivityManagementIds.Sections.LevelInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="LevelInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public LevelInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.LevelInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Number field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Int64? Number
		{
			get
			{
				var wrapper = section.GetValue<Int64>(SlcConnectivityManagementIds.Sections.LevelInfo.Number);
				if (wrapper != null)
				{
					return (Int64?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.LevelInfo.Number);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.LevelInfo.Number, (Int64)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.LevelInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.LevelInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.LevelInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the TransportType field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? TransportType
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType, (Guid)value);
				}
			}
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Int64>(SlcConnectivityManagementIds.Sections.LevelInfo.Number) == null)
				throw new InvalidOperationException("'Number' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.LevelInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType) == null)
				throw new InvalidOperationException("'TransportType' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}
}
