//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcConnectivityManagement
{
	using System;
	using System.ComponentModel;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	internal static class SlcConnectivityManagementIds
	{
		public const string ModuleId = "(slc)connectivity_management";
		public static class Enums
		{
			public enum LockState
			{
				Unlocked = 0,
				Locked = 1,
				Protected = 2
			}

			public enum Role
			{
				Source = 0,
				Destination = 1
			}
		}

		public static class Sections
		{
			public static class VirtualSignalGroupLevel
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("5e0dcb70-3dbc-479d-a127-c2e062e49b40"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Endpoint { get; } = new FieldDescriptorID(new Guid("6cbd74f3-e34f-48c7-a033-aaa16a0ba36e"));
				public static FieldDescriptorID Level { get; } = new FieldDescriptorID(new Guid("764c6435-04c7-448d-a2ec-0a4ea43b4b7d"));
			}

			public static class VirtualSignalGroupLock
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("1be3bdfe-3150-4352-b8b5-7030a66f0639"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID LockedBy { get; } = new FieldDescriptorID(new Guid("36eb43ed-5d2a-4d10-b12f-86059f29c43b"));
				public static FieldDescriptorID LockReason { get; } = new FieldDescriptorID(new Guid("c41f83c4-06ff-43e5-afd9-1be47ba0d7c9"));
				public static FieldDescriptorID LockJobReference { get; } = new FieldDescriptorID(new Guid("a62c3e0c-5cd2-457f-9ee8-494290fc3b82"));
				public static FieldDescriptorID LockTime { get; } = new FieldDescriptorID(new Guid("4b53fa79-7896-47ee-8be4-863194919ce3"));
				public static FieldDescriptorID LockState { get; } = new FieldDescriptorID(new Guid("86a72bf2-51d1-43e0-8d1b-0bc040ae7273"));
			}

			public static class VirtualSignalGroupStateInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("e698ff36-2ada-4773-ac93-4732a726537a"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID VirtualSignalGroupReference { get; } = new FieldDescriptorID(new Guid("7becf594-ff77-4530-8fa4-d64fed7a5bcc"));
			}

			public static class VirtualSignalGroupInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("a7d8863e-82d4-4bf3-a4c5-f34b1fb7eac0"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("f644dc13-d3e0-46df-b12d-4869c58e04f8"));
				public static FieldDescriptorID Description { get; } = new FieldDescriptorID(new Guid("e080c1da-879f-4cf1-973c-acbf01aca25c"));
				public static FieldDescriptorID Role { get; } = new FieldDescriptorID(new Guid("5b615da1-5772-4497-b0e9-2cdaf8822d65"));
				public static FieldDescriptorID Categories { get; } = new FieldDescriptorID(new Guid("3d419cab-6c82-4297-9199-d85a5ae12afb"));
			}

			public static class EndpointInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("4b094feb-3e2a-4539-ad1c-3e15c4dd7669"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("dabc33a4-0682-46f3-9b96-7b9c4abe2d4e"));
				public static FieldDescriptorID Role { get; } = new FieldDescriptorID(new Guid("10e9cf97-59e0-4c08-8cea-9f737a9ee7f8"));
				public static FieldDescriptorID Element { get; } = new FieldDescriptorID(new Guid("8c19dd88-d75a-42ea-928c-4508970778f4"));
				public static FieldDescriptorID Identifier { get; } = new FieldDescriptorID(new Guid("89cb7302-93f5-4c1e-ab97-d986c0353ad2"));
				public static FieldDescriptorID ControlElement { get; } = new FieldDescriptorID(new Guid("c1bda8e0-0380-4ecf-bb61-0db25ef8412a"));
				public static FieldDescriptorID ControlIdentifier { get; } = new FieldDescriptorID(new Guid("48575262-2b0b-404f-a4c7-22fd104e0426"));
				public static FieldDescriptorID TransportMetadata { get; } = new FieldDescriptorID(new Guid("b6fd7817-4524-420d-9497-8bb4edccdd9e"));
				public static FieldDescriptorID TransportType { get; } = new FieldDescriptorID(new Guid("64cc245e-5a0a-4479-9766-a93a7c090255"));
			}

			public static class TransportTypeInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("57558fef-283c-4b4d-84f8-f411a26e546c"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("2442cdc4-aa19-40b5-bb53-281f4a33aa74"));
			}

			public static class EndpointTransportMetadata
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("b622362c-51cd-48e0-8717-0a5e9a659c9d"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID FieldName { get; } = new FieldDescriptorID(new Guid("642c27f8-e882-4f12-843e-6f4595367fb0"));
				public static FieldDescriptorID Value { get; } = new FieldDescriptorID(new Guid("2ab6ddc7-444d-4edb-97cf-d9064738f001"));
			}

			public static class LevelInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("dd22ecda-43d1-40b5-b37a-45ab8ae5d3f9"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Number { get; } = new FieldDescriptorID(new Guid("07c316a4-0cd0-443e-98ce-7012d50a1f33"));
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("ddc1105e-2213-4ca9-bc1a-0077ee2cb198"));
				public static FieldDescriptorID TransportType { get; } = new FieldDescriptorID(new Guid("0154f612-029e-4b94-a92e-3572950bfe4d"));
			}

			public static class TransportTypeField
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("c71da817-f323-4ce2-a02a-91f29b83e6a8"))
				{ ModuleId = "(slc)connectivity_management" };
				public static FieldDescriptorID Name { get; } = new FieldDescriptorID(new Guid("021ce486-e060-4d71-b861-87f187597047"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId Level { get; } = new DomDefinitionId(new Guid("3a016709-8fe1-4ad6-aa1d-56873492b80b"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId Endpoint { get; } = new DomDefinitionId(new Guid("3d952eea-dd7f-4997-acec-af888160392a"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId VirtualSignalGroup { get; } = new DomDefinitionId(new Guid("f23a6e99-cb88-4282-bbbe-7ade9bc7fb04"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId VirtualSignalGroupState { get; } = new DomDefinitionId(new Guid("7a19a11c-3428-46b1-acfa-2ab0ef8c662f"))
			{ ModuleId = "(slc)connectivity_management" };
			public static DomDefinitionId TransportType { get; } = new DomDefinitionId(new Guid("91ddfbfe-00db-4244-b8e3-5a0a08fa3ced"))
			{ ModuleId = "(slc)connectivity_management" };
		}

		public static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcConnectivityManagement
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a LevelInstance DOM instance.
	/// The <see cref="LevelInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class LevelInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInstance"/> class. Creates an empty <see cref="LevelInstance"/> instance with default settings.
		/// </summary>
		public LevelInstance() : base(SlcConnectivityManagementIds.Definitions.Level)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInstance"/> class. Creates an empty <see cref="LevelInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public LevelInstance(Guid id) : base(SlcConnectivityManagementIds.Definitions.Level, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="LevelInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public LevelInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.Level))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.Level)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the LevelInfo section of the DOM Instance.
		/// </summary>
		public LevelInfoSection LevelInfo { get; set; }

		public static explicit operator LevelInstance(DomInstance instance)
		{
			return new LevelInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="LevelInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="LevelInstance"/> object that is a deep copy of this instance.</returns>
		public LevelInstance Clone()
		{
			return new LevelInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="LevelInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="LevelInstance"/> object that is a copy of this instance but with a different id.</returns>
		public LevelInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new LevelInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(LevelInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _levelInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.LevelInfo.Id));
			if (_levelInfo is null)
			{
				LevelInfo = new LevelInfoSection();
			}
			else
			{
				LevelInfo = new LevelInfoSection(_levelInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a EndpointInstance DOM instance.
	/// The <see cref="EndpointInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class EndpointInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInstance"/> class. Creates an empty <see cref="EndpointInstance"/> instance with default settings.
		/// </summary>
		public EndpointInstance() : base(SlcConnectivityManagementIds.Definitions.Endpoint)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInstance"/> class. Creates an empty <see cref="EndpointInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public EndpointInstance(Guid id) : base(SlcConnectivityManagementIds.Definitions.Endpoint, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="EndpointInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public EndpointInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.Endpoint))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.Endpoint)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the EndpointInfo section of the DOM Instance.
		/// </summary>
		public EndpointInfoSection EndpointInfo { get; set; }

		/// <summary>
		/// Gets or sets the EndpointTransportMetadata section of the DOM Instance.
		/// </summary>
		public IList<EndpointTransportMetadataSection> EndpointTransportMetadata { get; private set; }

		public static explicit operator EndpointInstance(DomInstance instance)
		{
			return new EndpointInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="EndpointInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="EndpointInstance"/> object that is a deep copy of this instance.</returns>
		public EndpointInstance Clone()
		{
			return new EndpointInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="EndpointInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="EndpointInstance"/> object that is a copy of this instance but with a different id.</returns>
		public EndpointInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new EndpointInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(EndpointInfo.ToSection());

			foreach (var item in EndpointTransportMetadata)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _endpointInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.EndpointInfo.Id));
			if (_endpointInfo is null)
			{
				EndpointInfo = new EndpointInfoSection();
			}
			else
			{
				EndpointInfo = new EndpointInfoSection(_endpointInfo);
			}

			EndpointTransportMetadata = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.Id)).Select(section => new EndpointTransportMetadataSection(section)).ToList();
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupInstance DOM instance.
	/// The <see cref="VirtualSignalGroupInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class VirtualSignalGroupInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInstance"/> class. Creates an empty <see cref="VirtualSignalGroupInstance"/> instance with default settings.
		/// </summary>
		public VirtualSignalGroupInstance() : base(SlcConnectivityManagementIds.Definitions.VirtualSignalGroup)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInstance"/> class. Creates an empty <see cref="VirtualSignalGroupInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public VirtualSignalGroupInstance(Guid id) : base(SlcConnectivityManagementIds.Definitions.VirtualSignalGroup, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="VirtualSignalGroupInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.VirtualSignalGroup))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.VirtualSignalGroup)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the VirtualSignalGroupLevel section of the DOM Instance.
		/// </summary>
		public IList<VirtualSignalGroupLevelSection> VirtualSignalGroupLevel { get; private set; }

		/// <summary>
		/// Gets or sets the VirtualSignalGroupInfo section of the DOM Instance.
		/// </summary>
		public VirtualSignalGroupInfoSection VirtualSignalGroupInfo { get; set; }

		public static explicit operator VirtualSignalGroupInstance(DomInstance instance)
		{
			return new VirtualSignalGroupInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="VirtualSignalGroupInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupInstance"/> object that is a deep copy of this instance.</returns>
		public VirtualSignalGroupInstance Clone()
		{
			return new VirtualSignalGroupInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="VirtualSignalGroupInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupInstance"/> object that is a copy of this instance but with a different id.</returns>
		public VirtualSignalGroupInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new VirtualSignalGroupInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			foreach (var item in VirtualSignalGroupLevel)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			domInstance.Sections.Add(VirtualSignalGroupInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			VirtualSignalGroupLevel = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Id)).Select(section => new VirtualSignalGroupLevelSection(section)).ToList();
			var _virtualSignalGroupInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Id));
			if (_virtualSignalGroupInfo is null)
			{
				VirtualSignalGroupInfo = new VirtualSignalGroupInfoSection();
			}
			else
			{
				VirtualSignalGroupInfo = new VirtualSignalGroupInfoSection(_virtualSignalGroupInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupStateInstance DOM instance.
	/// The <see cref="VirtualSignalGroupStateInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class VirtualSignalGroupStateInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupStateInstance"/> class. Creates an empty <see cref="VirtualSignalGroupStateInstance"/> instance with default settings.
		/// </summary>
		public VirtualSignalGroupStateInstance() : base(SlcConnectivityManagementIds.Definitions.VirtualSignalGroupState)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupStateInstance"/> class. Creates an empty <see cref="VirtualSignalGroupStateInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public VirtualSignalGroupStateInstance(Guid id) : base(SlcConnectivityManagementIds.Definitions.VirtualSignalGroupState, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupStateInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="VirtualSignalGroupStateInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupStateInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.VirtualSignalGroupState))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.VirtualSignalGroupState)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the VirtualSignalGroupLock section of the DOM Instance.
		/// </summary>
		public VirtualSignalGroupLockSection VirtualSignalGroupLock { get; set; }

		/// <summary>
		/// Gets or sets the VirtualSignalGroupStateInfo section of the DOM Instance.
		/// </summary>
		public VirtualSignalGroupStateInfoSection VirtualSignalGroupStateInfo { get; set; }

		public static explicit operator VirtualSignalGroupStateInstance(DomInstance instance)
		{
			return new VirtualSignalGroupStateInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="VirtualSignalGroupStateInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupStateInstance"/> object that is a deep copy of this instance.</returns>
		public VirtualSignalGroupStateInstance Clone()
		{
			return new VirtualSignalGroupStateInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="VirtualSignalGroupStateInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupStateInstance"/> object that is a copy of this instance but with a different id.</returns>
		public VirtualSignalGroupStateInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new VirtualSignalGroupStateInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			if (VirtualSignalGroupLock != null && !VirtualSignalGroupLock.IsEmpty)
			{
				domInstance.Sections.Add(VirtualSignalGroupLock.ToSection());
			}

			domInstance.Sections.Add(VirtualSignalGroupStateInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _virtualSignalGroupLock = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.Id));
			if (_virtualSignalGroupLock is null)
			{
				VirtualSignalGroupLock = new VirtualSignalGroupLockSection();
			}
			else
			{
				VirtualSignalGroupLock = new VirtualSignalGroupLockSection(_virtualSignalGroupLock);
			}

			var _virtualSignalGroupStateInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.VirtualSignalGroupStateInfo.Id));
			if (_virtualSignalGroupStateInfo is null)
			{
				VirtualSignalGroupStateInfo = new VirtualSignalGroupStateInfoSection();
			}
			else
			{
				VirtualSignalGroupStateInfo = new VirtualSignalGroupStateInfoSection(_virtualSignalGroupStateInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a TransportTypeInstance DOM instance.
	/// The <see cref="TransportTypeInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class TransportTypeInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInstance"/> class. Creates an empty <see cref="TransportTypeInstance"/> instance with default settings.
		/// </summary>
		public TransportTypeInstance() : base(SlcConnectivityManagementIds.Definitions.TransportType)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInstance"/> class. Creates an empty <see cref="TransportTypeInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public TransportTypeInstance(Guid id) : base(SlcConnectivityManagementIds.Definitions.TransportType, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="TransportTypeInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public TransportTypeInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcConnectivityManagementIds.Definitions.TransportType))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcConnectivityManagementIds.Definitions.TransportType)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the TransportTypeInfo section of the DOM Instance.
		/// </summary>
		public TransportTypeInfoSection TransportTypeInfo { get; set; }

		/// <summary>
		/// Gets or sets the TransportTypeField section of the DOM Instance.
		/// </summary>
		public IList<TransportTypeFieldSection> TransportTypeField { get; private set; }

		public static explicit operator TransportTypeInstance(DomInstance instance)
		{
			return new TransportTypeInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="TransportTypeInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="TransportTypeInstance"/> object that is a deep copy of this instance.</returns>
		public TransportTypeInstance Clone()
		{
			return new TransportTypeInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="TransportTypeInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="TransportTypeInstance"/> object that is a copy of this instance but with a different id.</returns>
		public TransportTypeInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new TransportTypeInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(TransportTypeInfo.ToSection());
			foreach (var item in TransportTypeField)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _transportTypeInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Id));
			if (_transportTypeInfo is null)
			{
				TransportTypeInfo = new TransportTypeInfoSection();
			}
			else
			{
				TransportTypeInfo = new TransportTypeInfoSection(_transportTypeInfo);
			}

			TransportTypeField = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcConnectivityManagementIds.Sections.TransportTypeField.Id)).Select(section => new TransportTypeFieldSection(section)).ToList();
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcConnectivityManagement
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupLevelSection section.
	/// The <see cref="VirtualSignalGroupLevelSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class VirtualSignalGroupLevelSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupLevelSection"/> class. Creates an empty <see cref="VirtualSignalGroupLevelSection"/> object with default settings.
		/// </summary>
		public VirtualSignalGroupLevelSection() : base(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupLevelSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="VirtualSignalGroupLevelSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupLevelSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Endpoint field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Endpoint
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Endpoint);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Endpoint);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Endpoint, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Level field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Level
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Level);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Level);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Level, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="VirtualSignalGroupLevelSection"/>.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupLevelSection"/> object that is a deep copy of this section.</returns>
		public VirtualSignalGroupLevelSection Clone()
		{
			return new VirtualSignalGroupLevelSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="VirtualSignalGroupLevelSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupLevelSection"/> object that is a copy of this section but with a different id.</returns>
		public VirtualSignalGroupLevelSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new VirtualSignalGroupLevelSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Endpoint) == null)
				throw new InvalidOperationException("'Endpoint' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLevel.Level) == null)
				throw new InvalidOperationException("'Level' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupLockSection section.
	/// The <see cref="VirtualSignalGroupLockSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class VirtualSignalGroupLockSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupLockSection"/> class. Creates an empty <see cref="VirtualSignalGroupLockSection"/> object with default settings.
		/// </summary>
		public VirtualSignalGroupLockSection() : base(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupLockSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="VirtualSignalGroupLockSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupLockSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.Id)
		{
		}

		/// <summary>
		/// Gets or sets the LockedBy field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String LockedBy
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockedBy);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockedBy);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockedBy, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the LockReason field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String LockReason
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockReason);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockReason);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockReason, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the LockJobReference field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String LockJobReference
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockJobReference);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockJobReference);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockJobReference, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the LockTime field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public DateTime? LockTime
		{
			get
			{
				var wrapper = section.GetValue<DateTime>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockTime);
				if (wrapper != null)
				{
					return (DateTime?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockTime);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockTime, (DateTime)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the LockState field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcConnectivityManagementIds.Enums.LockState? LockState
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockState);
				if (wrapper != null)
				{
					return (SlcConnectivityManagementIds.Enums.LockState?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockState);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockState, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="VirtualSignalGroupLockSection"/>.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupLockSection"/> object that is a deep copy of this section.</returns>
		public VirtualSignalGroupLockSection Clone()
		{
			return new VirtualSignalGroupLockSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="VirtualSignalGroupLockSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupLockSection"/> object that is a copy of this section but with a different id.</returns>
		public VirtualSignalGroupLockSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new VirtualSignalGroupLockSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockedBy) == null)
				throw new InvalidOperationException("'LockedBy' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<DateTime>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupLock.LockTime) == null)
				throw new InvalidOperationException("'LockTime' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupStateInfoSection section.
	/// The <see cref="VirtualSignalGroupStateInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class VirtualSignalGroupStateInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupStateInfoSection"/> class. Creates an empty <see cref="VirtualSignalGroupStateInfoSection"/> object with default settings.
		/// </summary>
		public VirtualSignalGroupStateInfoSection() : base(SlcConnectivityManagementIds.Sections.VirtualSignalGroupStateInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupStateInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="VirtualSignalGroupStateInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupStateInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.VirtualSignalGroupStateInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the VirtualSignalGroupReference field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? VirtualSignalGroupReference
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupStateInfo.VirtualSignalGroupReference);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupStateInfo.VirtualSignalGroupReference);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupStateInfo.VirtualSignalGroupReference, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="VirtualSignalGroupStateInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupStateInfoSection"/> object that is a deep copy of this section.</returns>
		public VirtualSignalGroupStateInfoSection Clone()
		{
			return new VirtualSignalGroupStateInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="VirtualSignalGroupStateInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupStateInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public VirtualSignalGroupStateInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new VirtualSignalGroupStateInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupStateInfo.VirtualSignalGroupReference) == null)
				throw new InvalidOperationException("'VirtualSignalGroupReference' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a VirtualSignalGroupInfoSection section.
	/// The <see cref="VirtualSignalGroupInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class VirtualSignalGroupInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInfoSection"/> class. Creates an empty <see cref="VirtualSignalGroupInfoSection"/> object with default settings.
		/// </summary>
		public VirtualSignalGroupInfoSection() : base(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Id)
		{
			Categories = new List<Guid>();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="VirtualSignalGroupInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="VirtualSignalGroupInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public VirtualSignalGroupInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Id)
		{
			var categories = section.GetListValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Categories);
			Categories = categories != null ? categories.Values : new List<Guid>();
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Description field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Description
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Description);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Description);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Description, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Role field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcConnectivityManagementIds.Enums.Role? Role
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role);
				if (wrapper != null)
				{
					return (SlcConnectivityManagementIds.Enums.Role?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Categories field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public IList<Guid> Categories { get; private set; }

		/// <summary>
		/// Creates a deep copy of the current <see cref="VirtualSignalGroupInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupInfoSection"/> object that is a deep copy of this section.</returns>
		public VirtualSignalGroupInfoSection Clone()
		{
			return new VirtualSignalGroupInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="VirtualSignalGroupInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="VirtualSignalGroupInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public VirtualSignalGroupInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new VirtualSignalGroupInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Role) == null)
				throw new InvalidOperationException("'Role' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (Categories.Count == 0)
				section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Categories);
			else
				section.AddOrUpdateListValue<Guid>(SlcConnectivityManagementIds.Sections.VirtualSignalGroupInfo.Categories, Categories.ToList());
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a EndpointInfoSection section.
	/// The <see cref="EndpointInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class EndpointInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInfoSection"/> class. Creates an empty <see cref="EndpointInfoSection"/> object with default settings.
		/// </summary>
		public EndpointInfoSection() : base(SlcConnectivityManagementIds.Sections.EndpointInfo.Id)
		{
			TransportMetadata = new List<Guid>();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="EndpointInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public EndpointInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.EndpointInfo.Id)
		{
			var transportMetadata = section.GetListValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportMetadata);
			TransportMetadata = transportMetadata != null ? transportMetadata.Values : new List<Guid>();
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Role field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcConnectivityManagementIds.Enums.Role? Role
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.EndpointInfo.Role);
				if (wrapper != null)
				{
					return (SlcConnectivityManagementIds.Enums.Role?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Role);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Role, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Element field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Element
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Element);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Element);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Element, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Identifier field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Identifier
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Identifier);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.Identifier);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.Identifier, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ControlElement field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ControlElement
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlElement);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlElement);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlElement, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ControlIdentifier field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String ControlIdentifier
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlIdentifier);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlIdentifier);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.ControlIdentifier, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the TransportMetadata field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public IList<Guid> TransportMetadata { get; private set; }

		/// <summary>
		/// Gets or sets the TransportType field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? TransportType
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="EndpointInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="EndpointInfoSection"/> object that is a deep copy of this section.</returns>
		public EndpointInfoSection Clone()
		{
			return new EndpointInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="EndpointInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="EndpointInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public EndpointInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new EndpointInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcConnectivityManagementIds.Sections.EndpointInfo.Role) == null)
				throw new InvalidOperationException("'Role' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (TransportMetadata.Count == 0)
				section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportMetadata);
			else
				section.AddOrUpdateListValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportMetadata, TransportMetadata.ToList());
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.EndpointInfo.TransportType) == null)
				throw new InvalidOperationException("'TransportType' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a TransportTypeInfoSection section.
	/// The <see cref="TransportTypeInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class TransportTypeInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInfoSection"/> class. Creates an empty <see cref="TransportTypeInfoSection"/> object with default settings.
		/// </summary>
		public TransportTypeInfoSection() : base(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="TransportTypeInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public TransportTypeInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.TransportTypeInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="TransportTypeInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="TransportTypeInfoSection"/> object that is a deep copy of this section.</returns>
		public TransportTypeInfoSection Clone()
		{
			return new TransportTypeInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="TransportTypeInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="TransportTypeInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public TransportTypeInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new TransportTypeInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a EndpointTransportMetadataSection section.
	/// The <see cref="EndpointTransportMetadataSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class EndpointTransportMetadataSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointTransportMetadataSection"/> class. Creates an empty <see cref="EndpointTransportMetadataSection"/> object with default settings.
		/// </summary>
		public EndpointTransportMetadataSection() : base(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="EndpointTransportMetadataSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="EndpointTransportMetadataSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public EndpointTransportMetadataSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.Id)
		{
		}

		/// <summary>
		/// Gets or sets the FieldName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String FieldName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.FieldName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.FieldName);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.FieldName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Value field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Value
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.Value);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.Value);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.Value, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="EndpointTransportMetadataSection"/>.
		/// </summary>
		/// <returns>A new <see cref="EndpointTransportMetadataSection"/> object that is a deep copy of this section.</returns>
		public EndpointTransportMetadataSection Clone()
		{
			return new EndpointTransportMetadataSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="EndpointTransportMetadataSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="EndpointTransportMetadataSection"/> object that is a copy of this section but with a different id.</returns>
		public EndpointTransportMetadataSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new EndpointTransportMetadataSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.EndpointTransportMetadata.FieldName) == null)
				throw new InvalidOperationException("'FieldName' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a LevelInfoSection section.
	/// The <see cref="LevelInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class LevelInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInfoSection"/> class. Creates an empty <see cref="LevelInfoSection"/> object with default settings.
		/// </summary>
		public LevelInfoSection() : base(SlcConnectivityManagementIds.Sections.LevelInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="LevelInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="LevelInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public LevelInfoSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.LevelInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Number field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Int64? Number
		{
			get
			{
				var wrapper = section.GetValue<Int64>(SlcConnectivityManagementIds.Sections.LevelInfo.Number);
				if (wrapper != null)
				{
					return (Int64?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.LevelInfo.Number);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.LevelInfo.Number, (Int64)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.LevelInfo.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.LevelInfo.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.LevelInfo.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the TransportType field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? TransportType
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="LevelInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="LevelInfoSection"/> object that is a deep copy of this section.</returns>
		public LevelInfoSection Clone()
		{
			return new LevelInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="LevelInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="LevelInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public LevelInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new LevelInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Int64>(SlcConnectivityManagementIds.Sections.LevelInfo.Number) == null)
				throw new InvalidOperationException("'Number' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.LevelInfo.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcConnectivityManagementIds.Sections.LevelInfo.TransportType) == null)
				throw new InvalidOperationException("'TransportType' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a TransportTypeFieldSection section.
	/// The <see cref="TransportTypeFieldSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class TransportTypeFieldSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeFieldSection"/> class. Creates an empty <see cref="TransportTypeFieldSection"/> object with default settings.
		/// </summary>
		public TransportTypeFieldSection() : base(SlcConnectivityManagementIds.Sections.TransportTypeField.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="TransportTypeFieldSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="TransportTypeFieldSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public TransportTypeFieldSection(Section section) : base(section, SlcConnectivityManagementIds.Sections.TransportTypeField.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Name field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String Name
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeField.Name);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcConnectivityManagementIds.Sections.TransportTypeField.Name);
				}
				else
				{
					section.AddOrUpdateValue(SlcConnectivityManagementIds.Sections.TransportTypeField.Name, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="TransportTypeFieldSection"/>.
		/// </summary>
		/// <returns>A new <see cref="TransportTypeFieldSection"/> object that is a deep copy of this section.</returns>
		public TransportTypeFieldSection Clone()
		{
			return new TransportTypeFieldSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="TransportTypeFieldSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="TransportTypeFieldSection"/> object that is a copy of this section but with a different id.</returns>
		public TransportTypeFieldSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new TransportTypeFieldSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcConnectivityManagementIds.Sections.TransportTypeField.Name) == null)
				throw new InvalidOperationException("'Name' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}
}
