//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcConnectivityManagement
{
	using System;
	using System.ComponentModel;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class SlcCategoriesIds
	{
		public const string ModuleId = "(slc)categories";
		public static class Enums
		{
		}

		public static class Sections
		{
		}

		public static class Definitions
		{
			public static DomDefinitionId Category { get; } = new DomDefinitionId(new Guid("51561163-340a-4953-97e0-bec5418fb559"))
			{ ModuleId = "(slc)categories" };
		}

		public static class Behaviors
		{
		}
	}
}
