//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcOrchestration
{
	using System;
	using System.ComponentModel;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	internal static class SlcOrchestrationIds
	{
		public const string ModuleId = "(slc)orchestration";
		public static class Enums
		{
			public enum EventType
			{
				Other = 0,
				Prerollstart = 1,
				Prerollstop = 2,
				Postrollstart = 3,
				Postrollstop = 4,
				Start = 5,
				Stop = 6
			}

			public enum EventState
			{
				Confirmed = 0,
				Configuring = 1,
				Cancelled = 2,
				Completed = 3,
				Failed = 4,
				Draft = 5
			}
		}

		public static class Sections
		{
			public static class ConfigurationInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("8686091c-ec37-46b4-b2c7-46965720defb"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID Configuration { get; } = new FieldDescriptorID(new Guid("4c3f6b83-c169-48f6-bc92-3b648d9f520c"));
			}

			public static class Connection
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("a99e83c5-e900-4f84-b0b1-5ce96a4ae540"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID DestinationNodeID { get; } = new FieldDescriptorID(new Guid("6edfcbfa-03b9-427b-88d3-f0b430cbe221"));
				public static FieldDescriptorID SourceNodeID { get; } = new FieldDescriptorID(new Guid("7ad73814-b725-4f71-9606-321862274ac3"));
				public static FieldDescriptorID LevelMapping { get; } = new FieldDescriptorID(new Guid("1dfdf771-0a08-4a85-9823-da52fe5732ff"));
				public static FieldDescriptorID DestinationVSG { get; } = new FieldDescriptorID(new Guid("4bb7c769-a76c-4320-b31a-1adbe4be6a16"));
				public static FieldDescriptorID SourceVSG { get; } = new FieldDescriptorID(new Guid("e17fa693-ecb6-4bf5-8226-ec58b42aede3"));
			}

			public static class GlobalConfiguration
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("adba49e4-3ab4-4c1c-bb12-929051dbcbf8"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID OrchestrationScriptName { get; } = new FieldDescriptorID(new Guid("6c30643d-dd3d-4eef-b95b-142cdabea2ea"));
				public static FieldDescriptorID OrchestrationScriptArguments { get; } = new FieldDescriptorID(new Guid("84d68b59-ef00-4e7d-9b96-bc80bb3fa001"));
				public static FieldDescriptorID OrchestrationProfile { get; } = new FieldDescriptorID(new Guid("9d3d1677-86bb-47d2-8284-2175e19fff0c"));
			}

			public static class NodeConfiguration
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("134f777d-389f-4f7f-b3a5-0314a0a5c544"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID NodeID { get; } = new FieldDescriptorID(new Guid("0b9e132d-82f1-4240-b20e-779988f59a03"));
				public static FieldDescriptorID NodeLabel { get; } = new FieldDescriptorID(new Guid("68aa7da1-bd0e-4350-b2ea-7ac5cc75f4a2"));
				public static FieldDescriptorID OrchestrationScriptName { get; } = new FieldDescriptorID(new Guid("dbe746a5-6043-46ea-ad76-be5d873ac4fb"));
				public static FieldDescriptorID OrchestrationScriptArguments { get; } = new FieldDescriptorID(new Guid("6fd2d3e0-0bef-4361-b181-b9bf25891df7"));
				public static FieldDescriptorID OrchestrationProfile { get; } = new FieldDescriptorID(new Guid("09651fc1-5fe3-4899-9386-9ca40bbff86d"));
			}

			public static class OrchestrationEventInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("43b3a199-8d6d-4cc9-ac63-3504f50e5ee5"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID EventName { get; } = new FieldDescriptorID(new Guid("b3a130e0-72cd-4936-bd53-3c614cb8e7b7"));
				public static FieldDescriptorID EventType { get; } = new FieldDescriptorID(new Guid("e85fbaf6-15a9-485c-92f3-d17cbe10f914"));
				public static FieldDescriptorID EventState { get; } = new FieldDescriptorID(new Guid("2d7ececb-585e-4786-8a89-329486b59f92"));
				public static FieldDescriptorID EventTime { get; } = new FieldDescriptorID(new Guid("184b3213-2839-472a-8438-84797fcc2e3b"));
				public static FieldDescriptorID JobInformation { get; } = new FieldDescriptorID(new Guid("8508f700-a734-4efa-a76a-1b220c71b2f6"));
				public static FieldDescriptorID FailureInfo { get; } = new FieldDescriptorID(new Guid("25395e30-97fd-44e3-9878-36f4fc64ec53"));
				public static FieldDescriptorID SchedulerReference { get; } = new FieldDescriptorID(new Guid("3a637566-62a1-4448-b1cc-66c1d8f29946"));
				public static FieldDescriptorID ActualStartTime { get; } = new FieldDescriptorID(new Guid("b344ff54-e25e-4bac-9d4f-9c8f241e9572"));
				public static FieldDescriptorID OrchestrationDuration { get; } = new FieldDescriptorID(new Guid("c584c1f5-a603-4d80-a449-e35f3dd2da95"));
			}

			public static class JobInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("3d776c06-b915-40df-bc10-a9c40b5f99e5"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID JobReference { get; } = new FieldDescriptorID(new Guid("e7bf0e2c-dc04-4620-8a19-eb24ede81b91"));
				public static FieldDescriptorID MonitoringService { get; } = new FieldDescriptorID(new Guid("1ad30bca-9282-49da-8d79-3acc197489ff"));
				public static FieldDescriptorID JobName { get; } = new FieldDescriptorID(new Guid("af147772-ca9c-4638-b28f-0f8db6cc7619"));
				public static FieldDescriptorID JobURL { get; } = new FieldDescriptorID(new Guid("771a106d-b114-441a-851e-57ed923dde4d"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId OrchestrationEvent { get; } = new DomDefinitionId(new Guid("f9085d46-a0f8-466a-8b97-bffb60e611d0"))
			{ ModuleId = "(slc)orchestration" };
			public static DomDefinitionId OrchestrationJobInfo { get; } = new DomDefinitionId(new Guid("f78aaf2c-2400-4af6-ae7b-1f7eff3e2ebf"))
			{ ModuleId = "(slc)orchestration" };
			public static DomDefinitionId Configuration { get; } = new DomDefinitionId(new Guid("b9c839e6-9167-4265-8483-43b192e49f93"))
			{ ModuleId = "(slc)orchestration" };
		}

		public static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcOrchestration
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a OrchestrationEventInstance DOM instance.
	/// The <see cref="OrchestrationEventInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class OrchestrationEventInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInstance"/> class. Creates an empty <see cref="OrchestrationEventInstance"/> instance with default settings.
		/// </summary>
		public OrchestrationEventInstance() : base(SlcOrchestrationIds.Definitions.OrchestrationEvent)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInstance"/> class. Creates an empty <see cref="OrchestrationEventInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public OrchestrationEventInstance(Guid id) : base(SlcOrchestrationIds.Definitions.OrchestrationEvent, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="OrchestrationEventInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public OrchestrationEventInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcOrchestrationIds.Definitions.OrchestrationEvent))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcOrchestrationIds.Definitions.OrchestrationEvent)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the ConfigurationInfo section of the DOM Instance.
		/// </summary>
		public ConfigurationInfoSection ConfigurationInfo { get; set; }

		/// <summary>
		/// Gets or sets the GlobalConfiguration section of the DOM Instance.
		/// </summary>
		public GlobalConfigurationSection GlobalConfiguration { get; set; }

		/// <summary>
		/// Gets or sets the OrchestrationEventInfo section of the DOM Instance.
		/// </summary>
		public OrchestrationEventInfoSection OrchestrationEventInfo { get; set; }

		public static explicit operator OrchestrationEventInstance(DomInstance instance)
		{
			return new OrchestrationEventInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="OrchestrationEventInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="OrchestrationEventInstance"/> object that is a deep copy of this instance.</returns>
		public OrchestrationEventInstance Clone()
		{
			return new OrchestrationEventInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="OrchestrationEventInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="OrchestrationEventInstance"/> object that is a copy of this instance but with a different id.</returns>
		public OrchestrationEventInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new OrchestrationEventInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			if (ConfigurationInfo != null && !ConfigurationInfo.IsEmpty)
			{
				domInstance.Sections.Add(ConfigurationInfo.ToSection());
			}

			if (GlobalConfiguration != null && !GlobalConfiguration.IsEmpty)
			{
				domInstance.Sections.Add(GlobalConfiguration.ToSection());
			}

			domInstance.Sections.Add(OrchestrationEventInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _configurationInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.ConfigurationInfo.Id));
			if (_configurationInfo is null)
			{
				ConfigurationInfo = new ConfigurationInfoSection();
			}
			else
			{
				ConfigurationInfo = new ConfigurationInfoSection(_configurationInfo);
			}

			var _globalConfiguration = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.GlobalConfiguration.Id));
			if (_globalConfiguration is null)
			{
				GlobalConfiguration = new GlobalConfigurationSection();
			}
			else
			{
				GlobalConfiguration = new GlobalConfigurationSection(_globalConfiguration);
			}

			var _orchestrationEventInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id));
			if (_orchestrationEventInfo is null)
			{
				OrchestrationEventInfo = new OrchestrationEventInfoSection();
			}
			else
			{
				OrchestrationEventInfo = new OrchestrationEventInfoSection(_orchestrationEventInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a OrchestrationJobInfoInstance DOM instance.
	/// The <see cref="OrchestrationJobInfoInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class OrchestrationJobInfoInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationJobInfoInstance"/> class. Creates an empty <see cref="OrchestrationJobInfoInstance"/> instance with default settings.
		/// </summary>
		public OrchestrationJobInfoInstance() : base(SlcOrchestrationIds.Definitions.OrchestrationJobInfo)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationJobInfoInstance"/> class. Creates an empty <see cref="OrchestrationJobInfoInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public OrchestrationJobInfoInstance(Guid id) : base(SlcOrchestrationIds.Definitions.OrchestrationJobInfo, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationJobInfoInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="OrchestrationJobInfoInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public OrchestrationJobInfoInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcOrchestrationIds.Definitions.OrchestrationJobInfo))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcOrchestrationIds.Definitions.OrchestrationJobInfo)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the JobInfo section of the DOM Instance.
		/// </summary>
		public JobInfoSection JobInfo { get; set; }

		public static explicit operator OrchestrationJobInfoInstance(DomInstance instance)
		{
			return new OrchestrationJobInfoInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="OrchestrationJobInfoInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="OrchestrationJobInfoInstance"/> object that is a deep copy of this instance.</returns>
		public OrchestrationJobInfoInstance Clone()
		{
			return new OrchestrationJobInfoInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="OrchestrationJobInfoInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="OrchestrationJobInfoInstance"/> object that is a copy of this instance but with a different id.</returns>
		public OrchestrationJobInfoInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new OrchestrationJobInfoInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			domInstance.Sections.Add(JobInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			var _jobInfo = domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.JobInfo.Id));
			if (_jobInfo is null)
			{
				JobInfo = new JobInfoSection();
			}
			else
			{
				JobInfo = new JobInfoSection(_jobInfo);
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a ConfigurationInstance DOM instance.
	/// The <see cref="ConfigurationInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class ConfigurationInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConfigurationInstance"/> class. Creates an empty <see cref="ConfigurationInstance"/> instance with default settings.
		/// </summary>
		public ConfigurationInstance() : base(SlcOrchestrationIds.Definitions.Configuration)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConfigurationInstance"/> class. Creates an empty <see cref="ConfigurationInstance"/> instance with default settings and a specific ID.
		/// </summary>
		public ConfigurationInstance(Guid id) : base(SlcOrchestrationIds.Definitions.Configuration, id)
		{
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConfigurationInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="ConfigurationInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ConfigurationInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcOrchestrationIds.Definitions.Configuration))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcOrchestrationIds.Definitions.Configuration)}'", nameof(domInstance));
			InitializeProperties();
			AfterLoad();
		}

		/// <summary>
		/// Gets or sets the Connection section of the DOM Instance.
		/// </summary>
		public IList<ConnectionSection> Connection { get; private set; }

		/// <summary>
		/// Gets or sets the NodeConfiguration section of the DOM Instance.
		/// </summary>
		public IList<NodeConfigurationSection> NodeConfiguration { get; private set; }

		public static explicit operator ConfigurationInstance(DomInstance instance)
		{
			return new ConfigurationInstance(instance);
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="ConfigurationInstance"/>.
		/// </summary>
		/// <returns>A new <see cref="ConfigurationInstance"/> object that is a deep copy of this instance.</returns>
		public ConfigurationInstance Clone()
		{
			return new ConfigurationInstance((DomInstance)this.ToInstance().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="ConfigurationInstance"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="ConfigurationInstance"/> object that is a copy of this instance but with a different id.</returns>
		public ConfigurationInstance Duplicate()
		{
			var instance = (DomInstance)this.ToInstance().Clone();
			instance.ID = new DomInstanceId(Guid.NewGuid())
			{ ModuleId = ModuleId };
			foreach (var section in instance.Sections)
			{
				section.ID = new Skyline.DataMiner.Net.Sections.SectionID(Guid.NewGuid());
			}

			return new ConfigurationInstance(instance);
		}

		/// <inheritdoc />
		protected sealed override DomInstance InternalToInstance()
		{
			domInstance.Sections.Clear();
			foreach (var item in Connection)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			foreach (var item in NodeConfiguration)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			return domInstance;
		}

		/// <inheritdoc />
		public sealed override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected sealed override void InitializeProperties()
		{
			Connection = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.Connection.Id)).Select(section => new ConnectionSection(section)).ToList();
			NodeConfiguration = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.NodeConfiguration.Id)).Select(section => new NodeConfigurationSection(section)).ToList();
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcOrchestration
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a ConfigurationInfoSection section.
	/// The <see cref="ConfigurationInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class ConfigurationInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConfigurationInfoSection"/> class. Creates an empty <see cref="ConfigurationInfoSection"/> object with default settings.
		/// </summary>
		public ConfigurationInfoSection() : base(SlcOrchestrationIds.Sections.ConfigurationInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConfigurationInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="ConfigurationInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ConfigurationInfoSection(Section section) : base(section, SlcOrchestrationIds.Sections.ConfigurationInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the Configuration field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? Configuration
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcOrchestrationIds.Sections.ConfigurationInfo.Configuration);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.ConfigurationInfo.Configuration);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.ConfigurationInfo.Configuration, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="ConfigurationInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="ConfigurationInfoSection"/> object that is a deep copy of this section.</returns>
		public ConfigurationInfoSection Clone()
		{
			return new ConfigurationInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="ConfigurationInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="ConfigurationInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public ConfigurationInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new ConfigurationInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<Guid>(SlcOrchestrationIds.Sections.ConfigurationInfo.Configuration) == null)
				throw new InvalidOperationException("'Configuration' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a ConnectionSection section.
	/// The <see cref="ConnectionSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class ConnectionSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionSection"/> class. Creates an empty <see cref="ConnectionSection"/> object with default settings.
		/// </summary>
		public ConnectionSection() : base(SlcOrchestrationIds.Sections.Connection.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="ConnectionSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ConnectionSection(Section section) : base(section, SlcOrchestrationIds.Sections.Connection.Id)
		{
		}

		/// <summary>
		/// Gets or sets the DestinationNodeID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String DestinationNodeID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.DestinationNodeID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.DestinationNodeID);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.DestinationNodeID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the SourceNodeID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String SourceNodeID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.SourceNodeID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.SourceNodeID);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.SourceNodeID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the LevelMapping field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String LevelMapping
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.LevelMapping);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.LevelMapping);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.LevelMapping, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the DestinationVSG field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? DestinationVSG
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcOrchestrationIds.Sections.Connection.DestinationVSG);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.DestinationVSG);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.DestinationVSG, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the SourceVSG field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? SourceVSG
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcOrchestrationIds.Sections.Connection.SourceVSG);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.SourceVSG);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.SourceVSG, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="ConnectionSection"/>.
		/// </summary>
		/// <returns>A new <see cref="ConnectionSection"/> object that is a deep copy of this section.</returns>
		public ConnectionSection Clone()
		{
			return new ConnectionSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="ConnectionSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="ConnectionSection"/> object that is a copy of this section but with a different id.</returns>
		public ConnectionSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new ConnectionSection(section);
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a GlobalConfigurationSection section.
	/// The <see cref="GlobalConfigurationSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class GlobalConfigurationSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="GlobalConfigurationSection"/> class. Creates an empty <see cref="GlobalConfigurationSection"/> object with default settings.
		/// </summary>
		public GlobalConfigurationSection() : base(SlcOrchestrationIds.Sections.GlobalConfiguration.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="GlobalConfigurationSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="GlobalConfigurationSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public GlobalConfigurationSection(Section section) : base(section, SlcOrchestrationIds.Sections.GlobalConfiguration.Id)
		{
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationScriptName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptName);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptArguments field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationScriptArguments
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptArguments);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptArguments);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptArguments, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationProfile field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationProfile
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationProfile);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationProfile);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationProfile, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="GlobalConfigurationSection"/>.
		/// </summary>
		/// <returns>A new <see cref="GlobalConfigurationSection"/> object that is a deep copy of this section.</returns>
		public GlobalConfigurationSection Clone()
		{
			return new GlobalConfigurationSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="GlobalConfigurationSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="GlobalConfigurationSection"/> object that is a copy of this section but with a different id.</returns>
		public GlobalConfigurationSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new GlobalConfigurationSection(section);
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a NodeConfigurationSection section.
	/// The <see cref="NodeConfigurationSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class NodeConfigurationSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="NodeConfigurationSection"/> class. Creates an empty <see cref="NodeConfigurationSection"/> object with default settings.
		/// </summary>
		public NodeConfigurationSection() : base(SlcOrchestrationIds.Sections.NodeConfiguration.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="NodeConfigurationSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="NodeConfigurationSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public NodeConfigurationSection(Section section) : base(section, SlcOrchestrationIds.Sections.NodeConfiguration.Id)
		{
		}

		/// <summary>
		/// Gets or sets the NodeID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String NodeID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the NodeLabel field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String NodeLabel
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.NodeLabel);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.NodeLabel);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.NodeLabel, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationScriptName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptName);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptArguments field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationScriptArguments
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptArguments);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptArguments);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptArguments, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationProfile field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationProfile
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationProfile);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationProfile);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationProfile, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="NodeConfigurationSection"/>.
		/// </summary>
		/// <returns>A new <see cref="NodeConfigurationSection"/> object that is a deep copy of this section.</returns>
		public NodeConfigurationSection Clone()
		{
			return new NodeConfigurationSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="NodeConfigurationSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="NodeConfigurationSection"/> object that is a copy of this section but with a different id.</returns>
		public NodeConfigurationSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new NodeConfigurationSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID) == null)
				throw new InvalidOperationException("'NodeID' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a OrchestrationEventInfoSection section.
	/// The <see cref="OrchestrationEventInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class OrchestrationEventInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInfoSection"/> class. Creates an empty <see cref="OrchestrationEventInfoSection"/> object with default settings.
		/// </summary>
		public OrchestrationEventInfoSection() : base(SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="OrchestrationEventInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public OrchestrationEventInfoSection(Section section) : base(section, SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the EventName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String EventName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the EventType field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcOrchestrationIds.Enums.EventType? EventType
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType);
				if (wrapper != null)
				{
					return (SlcOrchestrationIds.Enums.EventType?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the EventState field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcOrchestrationIds.Enums.EventState? EventState
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState);
				if (wrapper != null)
				{
					return (SlcOrchestrationIds.Enums.EventState?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the EventTime field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public DateTime? EventTime
		{
			get
			{
				var wrapper = section.GetValue<DateTime>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime);
				if (wrapper != null)
				{
					return (DateTime?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime, (DateTime)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the JobInformation field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? JobInformation
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobInformation);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobInformation);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobInformation, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the FailureInfo field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String FailureInfo
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.FailureInfo);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.FailureInfo);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.FailureInfo, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the SchedulerReference field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String SchedulerReference
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.SchedulerReference);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.SchedulerReference);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.SchedulerReference, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ActualStartTime field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public DateTime? ActualStartTime
		{
			get
			{
				var wrapper = section.GetValue<DateTime>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.ActualStartTime);
				if (wrapper != null)
				{
					return (DateTime?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.ActualStartTime);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.ActualStartTime, (DateTime)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationDuration field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public TimeSpan? OrchestrationDuration
		{
			get
			{
				var wrapper = section.GetValue<TimeSpan>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.OrchestrationDuration);
				if (wrapper != null)
				{
					return (TimeSpan?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.OrchestrationDuration);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.OrchestrationDuration, (TimeSpan)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="OrchestrationEventInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="OrchestrationEventInfoSection"/> object that is a deep copy of this section.</returns>
		public OrchestrationEventInfoSection Clone()
		{
			return new OrchestrationEventInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="OrchestrationEventInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="OrchestrationEventInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public OrchestrationEventInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new OrchestrationEventInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName) == null)
				throw new InvalidOperationException("'EventName' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType) == null)
				throw new InvalidOperationException("'EventType' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState) == null)
				throw new InvalidOperationException("'EventState' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<DateTime>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime) == null)
				throw new InvalidOperationException("'EventTime' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobInformation) == null)
				throw new InvalidOperationException("'JobInformation' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a JobInfoSection section.
	/// The <see cref="JobInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	internal partial class JobInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="JobInfoSection"/> class. Creates an empty <see cref="JobInfoSection"/> object with default settings.
		/// </summary>
		public JobInfoSection() : base(SlcOrchestrationIds.Sections.JobInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="JobInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="JobInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public JobInfoSection(Section section) : base(section, SlcOrchestrationIds.Sections.JobInfo.Id)
		{
		}

		/// <summary>
		/// Gets or sets the JobReference field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String JobReference
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.JobInfo.JobReference);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.JobInfo.JobReference);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.JobInfo.JobReference, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the MonitoringService field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String MonitoringService
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.JobInfo.MonitoringService);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.JobInfo.MonitoringService);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.JobInfo.MonitoringService, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the JobName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String JobName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.JobInfo.JobName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.JobInfo.JobName);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.JobInfo.JobName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the JobURL field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String JobURL
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.JobInfo.JobURL);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.JobInfo.JobURL);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.JobInfo.JobURL, (String)value);
				}
			}
		}

		/// <summary>
		/// Creates a deep copy of the current <see cref="JobInfoSection"/>.
		/// </summary>
		/// <returns>A new <see cref="JobInfoSection"/> object that is a deep copy of this section.</returns>
		public JobInfoSection Clone()
		{
			return new JobInfoSection((Section)this.ToSection().Clone());
		}

		/// <summary>
		/// Creates a duplicate of the current <see cref="JobInfoSection"/> with a new id.
		/// </summary>
		/// <returns>A new <see cref="JobInfoSection"/> object that is a copy of this section but with a different id.</returns>
		public JobInfoSection Duplicate()
		{
			var section = (Section)this.ToSection().Clone();
			section.ID = new SectionID(Guid.NewGuid());
			return new JobInfoSection(section);
		}

		/// <inheritdoc />
		protected override Section InternalToSection()
		{
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.JobInfo.JobReference) == null)
				throw new InvalidOperationException("'JobReference' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}
}
