//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcOrchestration
{
	using System;
	using System.ComponentModel;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class SlcOrchestrationIds
	{
		public const string ModuleId = "(slc)orchestration";
		public static class Enums
		{
			public enum EventType
			{
				Other = 0,
				Prerollstart = 1,
				Prerollstop = 2,
				Postrollstart = 3,
				Postrollstop = 4,
				Start = 5,
				Stop = 6
			}

			public enum EventState
			{
				Confirmed = 0,
				Configuring = 1,
				Cancelled = 2,
				Completed = 3,
				Failed = 4
			}
		}

		public static class Sections
		{
			public static class Connection
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("a99e83c5-e900-4f84-b0b1-5ce96a4ae540"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID SourceNodeID { get; } = new FieldDescriptorID(new Guid("7ad73814-b725-4f71-9606-321862274ac3"));
				public static FieldDescriptorID LevelMapping { get; } = new FieldDescriptorID(new Guid("1dfdf771-0a08-4a85-9823-da52fe5732ff"));
				public static FieldDescriptorID SourceVSG { get; } = new FieldDescriptorID(new Guid("e17fa693-ecb6-4bf5-8226-ec58b42aede3"));
				public static FieldDescriptorID DestinationNodeID { get; } = new FieldDescriptorID(new Guid("6edfcbfa-03b9-427b-88d3-f0b430cbe221"));
				public static FieldDescriptorID DestinationVSG { get; } = new FieldDescriptorID(new Guid("4bb7c769-a76c-4320-b31a-1adbe4be6a16"));
			}

			public static class GlobalConfiguration
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("adba49e4-3ab4-4c1c-bb12-929051dbcbf8"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID OrchestrationScriptName { get; } = new FieldDescriptorID(new Guid("6c30643d-dd3d-4eef-b95b-142cdabea2ea"));
				public static FieldDescriptorID OrchestrationScriptArguments { get; } = new FieldDescriptorID(new Guid("84d68b59-ef00-4e7d-9b96-bc80bb3fa001"));
			}

			public static class NodeConfiguration
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("134f777d-389f-4f7f-b3a5-0314a0a5c544"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID NodeID { get; } = new FieldDescriptorID(new Guid("0b9e132d-82f1-4240-b20e-779988f59a03"));
				public static FieldDescriptorID NodeLabel { get; } = new FieldDescriptorID(new Guid("68aa7da1-bd0e-4350-b2ea-7ac5cc75f4a2"));
				public static FieldDescriptorID OrchestrationScriptName { get; } = new FieldDescriptorID(new Guid("dbe746a5-6043-46ea-ad76-be5d873ac4fb"));
				public static FieldDescriptorID OrchestrationScriptArguments { get; } = new FieldDescriptorID(new Guid("6fd2d3e0-0bef-4361-b181-b9bf25891df7"));
			}

			public static class OrchestrationEventInfo
			{
				public static SectionDefinitionID Id { get; } = new SectionDefinitionID(new Guid("43b3a199-8d6d-4cc9-ac63-3504f50e5ee5"))
				{ ModuleId = "(slc)orchestration" };
				public static FieldDescriptorID EventName { get; } = new FieldDescriptorID(new Guid("b3a130e0-72cd-4936-bd53-3c614cb8e7b7"));
				public static FieldDescriptorID EventType { get; } = new FieldDescriptorID(new Guid("e85fbaf6-15a9-485c-92f3-d17cbe10f914"));
				public static FieldDescriptorID EventState { get; } = new FieldDescriptorID(new Guid("2d7ececb-585e-4786-8a89-329486b59f92"));
				public static FieldDescriptorID FailureInfo { get; } = new FieldDescriptorID(new Guid("25395e30-97fd-44e3-9878-36f4fc64ec53"));
				public static FieldDescriptorID EventTime { get; } = new FieldDescriptorID(new Guid("184b3213-2839-472a-8438-84797fcc2e3b"));
				public static FieldDescriptorID JobReference { get; } = new FieldDescriptorID(new Guid("8508f700-a734-4efa-a76a-1b220c71b2f6"));
				public static FieldDescriptorID ReservationInstance { get; } = new FieldDescriptorID(new Guid("3a637566-62a1-4448-b1cc-66c1d8f29946"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId OrchestrationEvent { get; } = new DomDefinitionId(new Guid("f9085d46-a0f8-466a-8b97-bffb60e611d0"))
			{ ModuleId = "(slc)orchestration" };
		}

		public static class Behaviors
		{
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcOrchestration
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Messages;

	/// <summary>
	/// Represents a wrapper class for accessing a OrchestrationEventInstance DOM instance.
	/// The <see cref="OrchestrationEventInstance"/> class provides simplified access to the data and functionality of the underlying DOM instance, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class OrchestrationEventInstance : DomInstanceBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInstance"/> class. Creates an empty <see cref="OrchestrationEventInstance"/> instance with default settings.
		/// </summary>
		public OrchestrationEventInstance() : base(SlcOrchestrationIds.Definitions.OrchestrationEvent)
		{
			InitializeProperties();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInstance"/> class using the specified <paramref name="domInstance"/> for initializing the object.
		/// </summary>
		/// <param name="domInstance">The <see cref="DomInstance"/> object that provides data for initializing the <see cref="OrchestrationEventInstance"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public OrchestrationEventInstance(DomInstance domInstance) : base(domInstance)
		{
			if (!domInstance.DomDefinitionId.Equals(SlcOrchestrationIds.Definitions.OrchestrationEvent))
				throw new ArgumentException($"The given domInstance, is not of type '{nameof(SlcOrchestrationIds.Definitions.OrchestrationEvent)}'", nameof(domInstance));
			InitializeProperties();
		}

		/// <summary>
		/// Gets or sets the Connection section of the DOM Instance.
		/// </summary>
		public IList<ConnectionSection> Connection { get; private set; }

		/// <summary>
		/// Gets or sets the GlobalConfiguration section of the DOM Instance.
		/// </summary>
		public GlobalConfigurationSection GlobalConfiguration { get; set; }

		/// <summary>
		/// Gets or sets the NodeConfiguration section of the DOM Instance.
		/// </summary>
		public IList<NodeConfigurationSection> NodeConfiguration { get; private set; }

		/// <summary>
		/// Gets or sets the OrchestrationEventInfo section of the DOM Instance.
		/// </summary>
		public OrchestrationEventInfoSection OrchestrationEventInfo { get; set; }

		public static explicit operator OrchestrationEventInstance(DomInstance instance)
		{
			return new OrchestrationEventInstance(instance);
		}

		/// <inheritdoc />
		public override DomInstance ToInstance()
		{
			domInstance.Sections.Clear();
			foreach (var item in Connection)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			if (!GlobalConfiguration.IsEmpty)
			{
				domInstance.Sections.Add(GlobalConfiguration.ToSection());
			}

			foreach (var item in NodeConfiguration)
			{
				domInstance.Sections.Add(item.ToSection());
			}

			domInstance.Sections.Add(OrchestrationEventInfo.ToSection());
			return domInstance;
		}

		/// <inheritdoc />
		public override void Save(DomHelper helper)
		{
			var exist = helper.DomInstances.Read(DomInstanceExposers.Id.Equal(domInstance.ID)).FirstOrDefault();
			var instance = ToInstance();
			if (exist == null)
			{
				domInstance = helper.DomInstances.Create(instance);
			}
			else
			{
				domInstance = helper.DomInstances.Update(instance);
			}
		}

		protected override void InitializeProperties()
		{
			Connection = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.Connection.Id)).Select(section => new ConnectionSection(section)).ToList();
			GlobalConfiguration = new GlobalConfigurationSection(domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.GlobalConfiguration.Id)));
			NodeConfiguration = domInstance.Sections.Where(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.NodeConfiguration.Id)).Select(section => new NodeConfigurationSection(section)).ToList();
			OrchestrationEventInfo = new OrchestrationEventInfoSection(domInstance.Sections.FirstOrDefault(section => section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id)));
		}
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DOM Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.MediaOps.Live.DOM.Model.SlcOrchestration
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;
	using Newtonsoft.Json;
	using Skyline.DataMiner.MediaOps.Live.API.Objects.SlcOrchestration;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Sections;

	/// <summary>
	/// Represents a wrapper class for accessing a ConnectionSection section.
	/// The <see cref="ConnectionSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class ConnectionSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionSection"/> class. Creates an empty <see cref="ConnectionSection"/> object with default settings.
		/// </summary>
		public ConnectionSection() : base(SlcOrchestrationIds.Sections.Connection.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ConnectionSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="ConnectionSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public ConnectionSection(Section section) : base(SlcOrchestrationIds.Sections.Connection.Id)
		{
			if (section == null)
			{
				return;
			}

			if (!section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.Connection.Id))
			{
				throw new ArgumentException($"The given section, is not of type '{nameof(SlcOrchestrationIds.Sections.Connection.Id)}'", nameof(section));
			}

			this.section = section;
		}

		/// <summary>
		/// Gets or sets the SourceNodeID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String SourceNodeID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.SourceNodeID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.SourceNodeID);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.SourceNodeID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the LevelMapping field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String LevelMapping
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.LevelMapping);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.LevelMapping);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.LevelMapping, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the SourceVSG field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? SourceVSG
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcOrchestrationIds.Sections.Connection.SourceVSG);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.SourceVSG);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.SourceVSG, (Guid)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the DestinationNodeID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String DestinationNodeID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.DestinationNodeID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.DestinationNodeID);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.DestinationNodeID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the DestinationVSG field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? DestinationVSG
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcOrchestrationIds.Sections.Connection.DestinationVSG);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.Connection.DestinationVSG);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.Connection.DestinationVSG, (Guid)value);
				}
			}
		}

		/// <inheritdoc />
		public override Section ToSection()
		{
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.SourceNodeID) == null)
				throw new InvalidOperationException("'SourceNodeID' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.LevelMapping) == null)
				throw new InvalidOperationException("'LevelMapping' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcOrchestrationIds.Sections.Connection.SourceVSG) == null)
				throw new InvalidOperationException("'SourceVSG' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.Connection.DestinationNodeID) == null)
				throw new InvalidOperationException("'DestinationNodeID' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcOrchestrationIds.Sections.Connection.DestinationVSG) == null)
				throw new InvalidOperationException("'DestinationVSG' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a GlobalConfigurationSection section.
	/// The <see cref="GlobalConfigurationSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class GlobalConfigurationSection : DomSectionBase
	{
		private List<OrchestrationScriptArgument> _nodeConfigurations;

		/// <summary>
		/// Initializes a new instance of the <see cref="GlobalConfigurationSection"/> class. Creates an empty <see cref="GlobalConfigurationSection"/> object with default settings.
		/// </summary>
		public GlobalConfigurationSection() : base(SlcOrchestrationIds.Sections.GlobalConfiguration.Id)
		{
			_nodeConfigurations = new List<OrchestrationScriptArgument>();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="GlobalConfigurationSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="GlobalConfigurationSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public GlobalConfigurationSection(Section section) : base(SlcOrchestrationIds.Sections.GlobalConfiguration.Id)
		{
			if (section == null)
			{
				return;
			}

			if (!section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.GlobalConfiguration.Id))
			{
				throw new ArgumentException($"The given section, is not of type '{nameof(SlcOrchestrationIds.Sections.GlobalConfiguration.Id)}'", nameof(section));
			}

			this.section = section;
			LoadNodeConfigurationListFromSection(section);
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationScriptName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptName);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptArguments field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public List<OrchestrationScriptArgument> OrchestrationScriptArguments
		{
			get
			{
				return _nodeConfigurations;
			}
		}

		/// <inheritdoc />
		public override Section ToSection()
		{
			WriteNodeConfigurationListToSection();

			return section;
		}

		private void LoadNodeConfigurationListFromSection(Section section)
		{
			var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptArguments);
			if (wrapper == null)
			{
				_nodeConfigurations = new List<OrchestrationScriptArgument>();
			}
			else
			{
				try
				{
					_nodeConfigurations = JsonConvert.DeserializeObject<List<OrchestrationScriptArgument>>((String)wrapper.Value);
				}
				catch
				{
					_nodeConfigurations = new List<OrchestrationScriptArgument>();
				}
			}
		}

		private void WriteNodeConfigurationListToSection()
		{
			if (_nodeConfigurations == null || !_nodeConfigurations.Any())
			{
				section.RemoveFieldValueById(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptArguments);
			}
			else
			{
				section.AddOrUpdateValue(SlcOrchestrationIds.Sections.GlobalConfiguration.OrchestrationScriptArguments, (String)JsonConvert.SerializeObject(_nodeConfigurations));
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a NodeConfigurationSection section.
	/// The <see cref="NodeConfigurationSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class NodeConfigurationSection : DomSectionBase
	{
		private List<OrchestrationScriptArgument> _nodeConfigurations;

		/// <summary>
		/// Initializes a new instance of the <see cref="NodeConfigurationSection"/> class. Creates an empty <see cref="NodeConfigurationSection"/> object with default settings.
		/// </summary>
		public NodeConfigurationSection() : base(SlcOrchestrationIds.Sections.NodeConfiguration.Id)
		{
			_nodeConfigurations = new List<OrchestrationScriptArgument>();
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="NodeConfigurationSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="NodeConfigurationSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public NodeConfigurationSection(Section section) : base(SlcOrchestrationIds.Sections.NodeConfiguration.Id)
		{
			if (section == null)
			{
				return;
			}

			if (!section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.NodeConfiguration.Id))
			{
				throw new ArgumentException($"The given section, is not of type '{nameof(SlcOrchestrationIds.Sections.NodeConfiguration.Id)}'", nameof(section));
			}

			this.section = section;
			LoadNodeConfigurationListFromSection(section);
		}

		/// <summary>
		/// Gets or sets the NodeID field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String NodeID
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the NodeLabel field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String NodeLabel
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.NodeLabel);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.NodeLabel);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.NodeLabel, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String OrchestrationScriptName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptName);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the OrchestrationScriptArguments field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public List<OrchestrationScriptArgument> OrchestrationScriptArguments
		{
			get
			{
				return _nodeConfigurations;
			}
		}

		/// <inheritdoc />
		public override Section ToSection()
		{
			WriteNodeConfigurationListToSection();

			if (section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.NodeID) == null)
				throw new InvalidOperationException("'NodeID' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.NodeLabel) == null)
				throw new InvalidOperationException("'NodeLabel' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}

		private void LoadNodeConfigurationListFromSection(Section section)
		{
			var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptArguments);
			if (wrapper == null)
			{
				_nodeConfigurations = new List<OrchestrationScriptArgument>();
			}
			else
			{
				try
				{
					_nodeConfigurations = JsonConvert.DeserializeObject<List<OrchestrationScriptArgument>>((String)wrapper.Value);
				}
				catch
				{
					_nodeConfigurations = new List<OrchestrationScriptArgument>();
				}
			}
		}

		private void WriteNodeConfigurationListToSection()
		{
			if (_nodeConfigurations == null || !_nodeConfigurations.Any())
			{
				section.RemoveFieldValueById(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptArguments);
			}
			else
			{
				section.AddOrUpdateValue(SlcOrchestrationIds.Sections.NodeConfiguration.OrchestrationScriptArguments, (String)JsonConvert.SerializeObject(_nodeConfigurations));
			}
		}
	}

	/// <summary>
	/// Represents a wrapper class for accessing a OrchestrationEventInfoSection section.
	/// The <see cref="OrchestrationEventInfoSection"/> class provides simplified access to the data and functionality of the underlying DOM section, allowing for easier manipulation and retrieval of data from DOM.
	/// </summary>
	public partial class OrchestrationEventInfoSection : DomSectionBase
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInfoSection"/> class. Creates an empty <see cref="OrchestrationEventInfoSection"/> object with default settings.
		/// </summary>
		public OrchestrationEventInfoSection() : base(SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OrchestrationEventInfoSection"/> class using the specified <paramref name="section"/> for initializing the object.
		/// </summary>
		/// <param name="section">The <see cref="Section"/> object that provides data for initializing the <see cref="OrchestrationEventInfoSection"/>. If the section is <c>null</c>, the constructor will not perform any initialization.</param>
		public OrchestrationEventInfoSection(Section section) : base(SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id)
		{
			if (section == null)
			{
				return;
			}

			if (!section.SectionDefinitionID.Equals(SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id))
			{
				throw new ArgumentException($"The given section, is not of type '{nameof(SlcOrchestrationIds.Sections.OrchestrationEventInfo.Id)}'", nameof(section));
			}

			this.section = section;
		}

		/// <summary>
		/// Gets or sets the EventName field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String EventName
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the EventType field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcOrchestrationIds.Enums.EventType? EventType
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType);
				if (wrapper != null)
				{
					return (SlcOrchestrationIds.Enums.EventType?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the EventState field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public SlcOrchestrationIds.Enums.EventState? EventState
		{
			get
			{
				var wrapper = section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState);
				if (wrapper != null)
				{
					return (SlcOrchestrationIds.Enums.EventState?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState, (Int32)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the FailureInfo field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String FailureInfo
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.FailureInfo);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.FailureInfo);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.FailureInfo, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the EventTime field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public DateTime? EventTime
		{
			get
			{
				var wrapper = section.GetValue<DateTime>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime);
				if (wrapper != null)
				{
					return (DateTime?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime, (DateTime)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the JobReference field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public String JobReference
		{
			get
			{
				var wrapper = section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobReference);
				if (wrapper != null)
				{
					return (String)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobReference);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobReference, (String)value);
				}
			}
		}

		/// <summary>
		/// Gets or sets the ReservationInstance field of the DOM Instance.
		/// </summary>
		/// <remarks>
		/// When retrieving the value:
		/// <list type="bullet">
		/// <item>If the field has been set, it will return the value.</item>
		/// <item>If the field is not set it will return <see langword="null"/>.</item>
		/// </list>
		/// When setting the value:
		/// <list type="bullet">
		/// <item>- If <see langword="null"/> is assigned, the field will be removed from the section.</item>
		/// <item>- If a valid value is assigned, the field value will be added or updated in the section.</item>
		/// </list>
		/// </remarks>
		public Guid? ReservationInstance
		{
			get
			{
				var wrapper = section.GetValue<Guid>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.ReservationInstance);
				if (wrapper != null)
				{
					return (Guid?)wrapper.Value;
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (value == null)
				{
					section.RemoveFieldValueById(SlcOrchestrationIds.Sections.OrchestrationEventInfo.ReservationInstance);
				}
				else
				{
					section.AddOrUpdateValue(SlcOrchestrationIds.Sections.OrchestrationEventInfo.ReservationInstance, (Guid)value);
				}
			}
		}

		/// <inheritdoc />
		public override Section ToSection()
		{
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventName) == null)
				throw new InvalidOperationException("'EventName' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventType) == null)
				throw new InvalidOperationException("'EventType' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Int32>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventState) == null)
				throw new InvalidOperationException("'EventState' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<DateTime>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.EventTime) == null)
				throw new InvalidOperationException("'EventTime' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<String>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.JobReference) == null)
				throw new InvalidOperationException("'JobReference' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			if (section.GetValue<Guid>(SlcOrchestrationIds.Sections.OrchestrationEventInfo.ReservationInstance) == null)
				throw new InvalidOperationException("'ReservationInstance' is required. Please fill it in before saving, or mark it as optional with the DOM Editor.");
			return section;
		}
	}
}
